### ISSUE TITLE
Add a mechanism to store data related to an Area (validity period and more)

### ISSUE THREAD

**Issue by RobertoMaurizzi** [catalpainternational/simple_locations#40]
# Description
In [DIRD](https://github.com/catalpainternational/openly_dird/issues/2054) and Liga Inan we found ourselves having to create new Districts/Municipalities to follow the need of the governments in how they manage their administrative regions.
It would be very nice to add metadata to Area objects so we can track when they were active and other information about them, follwing the Dublin Core metadata conventions where possible/sensible (part of that information is already included in Area or related models).

See [this document](https://www.dublincore.org/resources/metadata-basics/#:~:text=fifteen%20generic%2C%20widely%20used%20elements%20%2D%2D%20Creator%2C%20Contributor%2C%20Publisher%2C%20Title%2C%20Date%2C%20Language%2C%20Format%2C%20Subject%2C%20Description%2C%20Identifier%2C%20Relation%2C%20Source%2C%20Type%2C%20Coverage%2C%20and%20Rights) for Dublin Core and the metadata it includes.

**Comment by RobertoMaurizzi** [comment]
After more than a bit of back and forth, I'd say that using PostgreSQL's `daterange` type should permit to have a decent solution. Version 14 and up even have `datemultirange` that would make things even easier but 1) there's no Django field support 2) it's easy enough to get a list of ranges and convert them to a multirange (see this [article](https://www.crunchydata.com/blog/better-range-types-in-postgres-14-turning-100-lines-of-sql-into-3)).

Other data from DC might be better served by a JSONField, but as mentioned we probably have half of them already either in Area itself or linked from application specific models (Openly does track many of the same data in its own way).

The other decision to take is: do we link Areas to Netadata, or the other way around? Advantages of the first approach is that the most common starting situation (all Areas have the same metadata) is very easy to manage, while the second approach would require to create Metadata items then link them to all the Areas (assuming a M2M relation between Metadata and Area). This has the advantage that the Area model/table won't need additional fields.

In other words something like this:

```python
from django.contrib.postgres.fields import DateRangeField
from psycopg2.extras import DateRange

class Metadata(models.Model):
    # Dublin Core elements
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    date = DateRangeField(default=DateRange(date(1975, 9, 15), date(2999, 12, 31)))
    location =models.ManyToManyField(Area)  # We shouldn't delete areas...

    # JSONField for other non-categorical data: Contributor, Publisher, Title, Language, Format, Subject, Description, Identifier, Source,, Rights
    data = models.JSONField(blank=True, null=True)

    def __str__(self):
        return f"Metadata - ID: {self.pk}"
```

The REAL can of worms however is how to manage changes that remove rows from the table:
 - An area is deleted (rejoins adjacent Area, region becomes independent): There's the need to keep all the old information around for queries that need to consider the past situation.
 -  An area gets split in 2: we should keep the OLD version of the area together with the 2 new derivative Areas.  In addition to the above, this will likely cause problem with unique constraints on `code` and possibly other things.
 - Parent-child dependencies: how to store that children areas have moved from one Area to another?

While we don't need to solve all those problems here and now (we'll be happy with just the validity dates) it would be nice to implement anything that's easy to do and keep in mind the other possibilities so we don't block some of the possible ways to implement them in the future.

**Comment by raphaelmerx** [comment]
> While we don't need to solve all those problems here and now

Indeed, don't think it's worth over-complicating the code to support these use cases. For now the one use case to support is the creation of a new area by splitting one existing area into two. 

> we should keep the OLD version of the area together with the 2 new derivative Areas

don't think we need to, what we do in the dird `create_new_districts_2022` command works fine

Adding a `DateRangeField`, like you have above, on the `Area` model should suffice.
